// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHR7NqkKqpjRoc6mwcLf9fu_nEeQMZcmI',
    appId: '1:342445214471:web:3eff36ae2d893317e1d3a2',
    messagingSenderId: '342445214471',
    projectId: 'weatherly-app-bc6fd',
    authDomain: 'weatherly-app-bc6fd.firebaseapp.com',
    storageBucket: 'weatherly-app-bc6fd.firebasestorage.app',
    measurementId: 'G-TQXE51SLY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9iFUxYc-0KTRbyokRwwDxRQXl8o3T6ug',
    appId: '1:342445214471:android:871234329118f02de1d3a2',
    messagingSenderId: '342445214471',
    projectId: 'weatherly-app-bc6fd',
    storageBucket: 'weatherly-app-bc6fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhjuXdCTigBF17c-edtUphVpd90pUMms',
    appId: '1:342445214471:ios:73a624c107b1a851e1d3a2',
    messagingSenderId: '342445214471',
    projectId: 'weatherly-app-bc6fd',
    storageBucket: 'weatherly-app-bc6fd.firebasestorage.app',
    iosBundleId: 'com.example.weatherlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANhjuXdCTigBF17c-edtUphVpd90pUMms',
    appId: '1:342445214471:ios:73a624c107b1a851e1d3a2',
    messagingSenderId: '342445214471',
    projectId: 'weatherly-app-bc6fd',
    storageBucket: 'weatherly-app-bc6fd.firebasestorage.app',
    iosBundleId: 'com.example.weatherlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHR7NqkKqpjRoc6mwcLf9fu_nEeQMZcmI',
    appId: '1:342445214471:web:8860e82b0b94954ee1d3a2',
    messagingSenderId: '342445214471',
    projectId: 'weatherly-app-bc6fd',
    authDomain: 'weatherly-app-bc6fd.firebaseapp.com',
    storageBucket: 'weatherly-app-bc6fd.firebasestorage.app',
    measurementId: 'G-P020M0Y0SW',
  );
}
